services:
  postgres:
    image: postgres:16
    container_name: station-manager-postgres
    environment:
      POSTGRES_DB: station_manager
      POSTGRES_USER: station_manager
      POSTGRES_PASSWORD: station_manager
    ports:
      - "5432:5432"
    volumes:
      - station_manager_postgres_data:/var/lib/postgresql/data

volumes:
  station_manager_postgres_data: