services:
  postgres:
    image: postgres:16
    container_name: station-manager-postgres
    environment:
      POSTGRES_DB: station_manager
      POSTGRES_USER: station_manager
      POSTGRES_PASSWORD: station_manager
    ports:
      - "5432:5432"
    volumes:
      - station_manager_postgres_data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: station-manager-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - station_manager_keycloak_data:/opt/keycloak/data
volumes:
  station_manager_postgres_data:
  station_manager_keycloak_data: